Diplom1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diplom1.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Diplom1/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Diplom1.Models;

namespace Diplom1.Controllers
{
    [Authorize(Roles ="user")]
    public class OrdersController : Controller
    {
        private ServiceStationContext db = new ServiceStationContext();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Worker);
            orders = orders.Include(o => o.Job);
            orders = orders.Include(o => o.Person);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            order.Job = db.Jobs.Find(order.JobId);
            order.Worker = db.Workers.Find(order.WorkerId);
            order.Person = db.Persons.Find(order.PersonId);
            return View(order);
        }

        [HttpPost]
        public ActionResult Details(int id)
        {
            Order order = db.Orders.Find(id);
            if (order.Status == "Заявка")
            {
                order.Status = "Подтверждён";
            }
            else
            {
                if (order.Status == "Подтверждён")
                {
                    order.Status = "Контроль исполнения";
                }
                else
                {
                    if (order.Status == "Контроль исполнения")
                    {
                        order.Status = "Выполнен";
                    }
                }
            }
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Create()
        {
            ViewBag.Jobs = db.Jobs.ToList();
            ViewBag.Days = db.Days.ToList();
            db.Jobs.ToList().Select(c => c.Name);
            return View();
        }

        // POST: Orders/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Car,Date,PesonId,JobId,Comment,Status")] Order order, Person person, int jobId)
        {
            if (ModelState.IsValid)
            {
                if (db.Persons.Any(p => p.Phone == person.Phone))
                {
                    foreach (Person p in db.Persons.Where(s => s.Phone == person.Phone))
                    {
                        p.Name = person.Name;
                        person.Id = p.Id;
                        db.Entry(p).State = EntityState.Modified;
                    }
                }
                else
                {
                    db.Persons.Add(person);
                }
                db.SaveChanges();
                order.Status = "Заявка";
                order.JobId = jobId;
                order.PersonId = person.Id;
                db.Orders.Add(order);
                db.SaveChanges();
                if(User.Identity.IsAuthenticated==false)
                {
                    return Redirect("/home/");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

            return View(order);
        }


        [Authorize(Roles = "manager")]
        public ActionResult Edit(int? id)
        {
            if(User.IsInRole("manager") == false)
            {
                Response.StatusCode = 403;
                return View();
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            var q = from f in db.Workers where f.Days.Any(g => g.Id == 1) select f;
            foreach (Worker c in db.Workers.Where((d => d.Days.Any(e => e.Id == 1) && d.Jobs.Any(e => e.Id == 1))))
            {
                string a = c.Name;
            }
            ViewBag.Jobs = db.Jobs.ToList();
            ViewBag.Days = db.Days.ToList();
            ViewBag.Workers = db.Workers.ToList();
            return View(order);
        }

        // POST: Orders/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Car,Date,PersonId,JobId,Comment,Status,WorkerId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public PartialViewResult WorkerDropDown(int orderId, int jobId, string day)
        {
            ViewBag.Jobs = db.Jobs.ToList();
            ViewBag.Days = db.Days.ToList();
            ViewBag.Workers = db.Workers.ToList();
            ViewBag.JobId = jobId;
            ViewBag.Day = DateTime.Parse(day).DayOfWeek;
            return PartialView("WorkerDropDown", db.Orders.Find(orderId));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Diplom1/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Diplom1.Models;

namespace Diplom1.Controllers
{
    [Authorize(Roles = "manager")]
    public class PeopleController : Controller
    {
        private ServiceStationContext db = new ServiceStationContext();

        // GET: People
        public ActionResult Index()
        {
            return View(db.Persons.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Phone")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Diplom1/Controllers/SpecialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diplom1.Controllers
{
    public class SpecialController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Diplom1/Views/Shared/_Layout.cshtml
@using Diplom1.Models
@using Diplom1.Helper

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="icon" type="image/png" href="/img/AIRMOTORS-LOGO.png" />
</head>
<body id="container">
    <header>
        <div class="main-header">
            <div class="wrapper">
                <nav id="absolute-nav" class="navbar navbar-default">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" rel="home" href="/" title="Главная">
                                @Html.Image("/img/AIRMOTORS-LOGO.png", "Главная")
                            </a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav menu">
                                <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                                <li>@Html.ActionLink("Услуги", "Index", "Services")</li>
                                <li>@Html.ActionLink("Акции", "Index", "Special")</li>
                                <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                                <li>@Html.ActionLink("О нас", "Index", "About")</li>
                                <li>@Html.ActionLink("Записаться на СТО", "Index", "Zapisatsa")</li>
                            </ul>

                            <ul class="nav navbar-nav menu">
                                @if (Request.IsAuthenticated)
                                {
                                    if (User.IsInRole("user") == true)
                                    {
                                        <li>@Html.ActionLink("Заказы", "Index", "Orders")</li>
                                    }
                                    if (User.IsInRole("manager") == true)
                                    {
                                        <li>@Html.ActionLink("Клиенты", "Index", "People")</li>
                                        <li>@Html.ActionLink("Сотрудники", "Index", "Workers")</li>
                                    }
                                    if (User.IsInRole("admin") == true)
                                    {
                                        <li>@Html.ActionLink("Пользователи", "Index", "Account")</li>
                                    }

                                    <li><p>Здравствуйте, @User.Identity.Name!</p></li>
                                    <li><a href="/account/logoff">Выйти</a></li>
                                }

                            </ul>
</div>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <div class="body-content">
        @RenderBody()
    </div>
    <div id="footer">
        <div class="wrapper main-footer">
            <div class="container copyright">
                <ul class="list-inline pull-left">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                    <li>@Html.ActionLink("О нас", "Index", "About")</li>
                </ul>
                <p class="pull-right">Разаработка и продвижение: <a title="Андрей Коляда" href="https://www.linkedin.com/in/andrey-kolyada-846184202/">Андрей Коляда</a></p>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Diplom1/Views/Shared/_LayoutBack.cshtml
@using Diplom1.Models
@using Diplom1.Helper

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="icon" type="image/png" href="/img/AIRMOTORS-LOGO.png" />
</head>
<body id="container">
    <header>
        <div class="main-header">
            <div class="wrapper">
                <nav id="absolute-nav" class="navbar navbar-default">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" rel="home" href="/" title="Главная">
                                @Html.Image("/img/AIRMOTORS-LOGO.png", "Главная")
                            </a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav menu">
                                <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                                <li>@Html.ActionLink("Услуги", "Index", "Services")</li>
                                <li>@Html.ActionLink("Акции", "Index", "Special")</li>
                                <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                                <li>@Html.ActionLink("О нас", "Index", "About")</li>
                                <li>@Html.ActionLink("Записаться на СТО", "Index", "Zapisatsa")</li>
                            </ul>

                            <ul class="nav navbar-nav menu">
                                @if (Request.IsAuthenticated)
                                {
                                    if (User.IsInRole("user") == true)
                                    {
                                        <li>@Html.ActionLink("Заказы", "Index", "Orders")</li>
                                    }
                                    if (User.IsInRole("manager") == true)
                                    {
                                        <li>@Html.ActionLink("Клиенты", "Index", "People")</li>
                                        <li>@Html.ActionLink("Сотрудники", "Index", "Workers")</li>
                                    }
                                    if (User.IsInRole("admin") == true)
                                    {
                                        <li>@Html.ActionLink("Пользователи", "Index", "Account")</li>
                                    }

                                    <li><p>Здравствуйте, @User.Identity.Name!</p></li>
                                    <li><a href="/account/logoff">Выйти</a></li>
                                }

                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="page-header">
            <h1>@ViewBag.Title</h1>
        </div>
    </header>
    <div class="body-content container">
        @RenderBody()
    </div>
    <div id="footer">
        <div class="wrapper main-footer">
            <div class="container copyright">
                <ul class="list-inline pull-left">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                    <li>@Html.ActionLink("О нас", "Index", "About")</li>
                </ul>
                <p class="pull-right">Разаработка и продвижение: <a title="Андрей Коляда" href="https://www.linkedin.com/in/andrey-kolyada-846184202/">Андрей Коляда</a></p>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Diplom1/Views/Shared/_LayoutService.cshtml
@using Diplom1.Helper
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section-md section-bordered">
    <div class="container" id="content">
        <div class="row">
            @RenderBody()
            <div class="col-md-4">
                <div id="services-list">
                    <ul class="list-unstyled">
                        <li>
                            <h3>Автокондиционеры</h3>
                            <ul class='children'>
                                <li><a href="~/Services/conditioner/">Заправка, дезинфекция и обслуживание автокондиционеров</a></li>
                            </ul>
                        </li>
                        <li>
                            <h3>Диагностика и контроль</h3>
                            <ul class='children'>
                                <li><a href="~/Services/diagnostikatormozov/">Диагностика тормозной системы</a></li>
                                <li><a href="~/Services/DiagnostikaPodveski/">Диагностика подвески</a></li>
                                <li><a href="~/Services/CompDiagnostika/">Компьютерная диагностика</a></li>
                                <li><a href="~/Services/RazvalShozhdenie/">Развал-схождение 3D</a></li>
                            </ul>
                        </li>
                        <li>
                            <h3>Ремонт и замена элементов</h3>
                            <ul class='children'>
                                <li><a href="~/Services/RemontRulya/">Ремонт рулевого управления</a></li>
                                <li><a href="~/Services/RemontTormozov/">Ремонт тормозной системы</a></li>
                                <li><a href="~/Services/RemontPodveski/">Ремонт подвески</a></li>
                                <li><a href="~/Services/RemontKpp/">Ремонт или замена коробок передач (КПП, АКПП)</a></li>
                                <li><a href="~/Services/RemontDvs/">Ремонт или замена двигателя внутреннего сгорания</a></li>
                            </ul>
                        </li>
                        <li>
                            <h3>Техническое обслуживание</h3>
                            <ul class='children'>
                                <li><a href="~/Services/ZamenaMasla/">Замена масла и других технических жидкостей</a></li>
                                <li><a href="~/Services/ZamenaFiltrov/">Замена фильтров в автомобиле</a></li>
                                <li><a href="~/Services/Shinomontazh/">Шиномонтаж</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        <li><h3>Запись на СТО по телефонам</h3></li>
                        <li><span class="mobo-velcom-16"></span>+375 29 336-18-06</li>
                        <li><span class="mobo-mts-16"></span>+375 33 336-18-06</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</section>